### ISSUE TITLE
Enable alerting on OOMs

### ISSUE THREAD

**Issue by rocketraman** [kubernetes-monitoring/kubernetes-mixin#112]
The next version of kube-state-metrics should have a metric called kube_pod_container_status_last_terminated_reason. See https://github.com/kubernetes/kube-state-metrics/pull/535.

Can an OOM alert based on this metric be setup in this mixin?

**Comment by BrianChristie** [comment]
Currently it appears to be difficult to create a good alert on Out Of Memory crash looping pods, because `kube_pod_container_status_last_terminated_reason` is a binary gauge, but should be a counter.

This has been brought up with sig-node and sig-instrumentation, and it appears a fix requires changes to the Kubelet to expose this counter (as well as a Pod event). This will probably take a significant period of time to get done and merged, see: https://github.com/kubernetes/kubernetes/issues/69676#issuecomment-442391695 . 

As far as I can see, in the interim the best that could be done is an alert if the Pod has a status of `OOMKilled` a single time, but there's no way to only alert based on the Pod crashing with that status on multiple occasions over a period of time.

**Comment by wking** [comment]
#510 and #800 are both opened to poke at this.  I haven't read either closely enough to compare and contrast, but thought I'd drop some cross-references.
