### ISSUE TITLE
Vendoring kubernetes-mixin with jb takes 17.2MB

### ISSUE THREAD

**Issue by dlespiau** [kubernetes-monitoring/kubernetes-mixin#129]
When `jb` vendors `kubernetes-mixin`, it includes the `.circleci` directory which has a copy of the `jsonnet` binary. It'd be nice to not have binary around when vendoring this repo.

**Comment by metalmatze** [comment]
Having the binary in the repository actually looks like a mistake to me, as circleci is runnnig a `curl` to fetch the binary.
@tomwilkie is that in there on purpose?

**Comment by metalmatze** [comment]
We still need the C++ version for now, as we want to check the files in PRs with `jsonnet fmt` which is only supported by that.
However, we should be able to pull a specific version of that in CI rather than committing a binary, I believe. Interested in hearing why @tomwilkie committed that binary though.

**Comment by metalmatze** [comment]
Personally I don't have a huge problem with it. This is one of the smaller repositories :man_shrugging:

**Comment by dlespiau** [comment]
I don't think it's a good idea to rewrite the history :) people can go and vendor a more recent version. I think we should consider this issue fixed!
