### ISSUE TITLE
v0.1.0 not pinned to stable dependency versions

### ISSUE THREAD

**Issue by rscott231** [kubernetes-monitoring/kubernetes-mixin#228]
The jsonnetfile for the v0.1.0 release specifies master as the version all dependencies and no `jsonnetfile.lock.json` exists. This opens up a few possible problems:
* If the master versions of the upstream dependencies ever make breaking changes to APIs, v0.1.0 of kubernetes mixin will break
* Projects that use lock files and vendor in kubernetes-mixin plus either grafana-builder or grafonnet as transitive dependencies are more prone to dependency conflicts as master versions of the latter two drift.

Suggestion: cut a v0.1.0 release with either specific versions in the jsonnetfile or a lock file

**Comment by brancz** [comment]
Do you have a concrete problem or is this theoretical?

**Comment by rscot231** [comment]
It's a concrete problem that we have worked around for the moment.

`A` has dependencies on `kubernetes-mixin` and `B`. `B` uses a lock file and also has a dependency on `kubernetes-mixin`. Grafonnet [added a commit two days ago](https://github.com/grafana/grafonnet-lib/commits/master) that bumped the SHA. `jb update` in `A` failed because `kubernetes-mixin` has a dependency on Grafonnet master and `B` is locked to whatever SHA was on master last time a `jb update` was run in that repo. The versions therefore no longer match and `jb` fails because of the "[diamond problem](https://github.com/jsonnet-bundler/jsonnet-bundler#current-limitations)".

We have worked around it for now by gitignoring the lock file in `B`. It doesn't cause us any issues at the moment to do so.

Transitive dependencies are hard.

Also, my suggestion in the first post is wrong - I meant to suggest cutting a v0.1.1 not overwriting 0.1.0.

**Comment by brancz** [comment]
Nothing should have a checked-in lock file that is not your "end-usage". Is this an open source thing doing that? (if this is [kube-prometheus](https://github.com/coreos/kube-prometheus), then you may be importing the wrong thing as the lockfile in the root of the repo is just an example, the import should happen against the [jsonnet/kube-prometheus](https://github.com/coreos/kube-prometheus/tree/master/jsonnet/kube-prometheus) path). Eventually version constraints should be introduced in jb though.
