### ISSUE TITLE
Change Alert Rule Duration ex. KubeNodeNotReady from 1h to 15m

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes-monitoring/kubernetes-mixin#236]
Is it possible to change the duration of the alerts. We would like to lower the duration of alerts such as the KubeNodeNotReady from 1h to 15m where 1h is too long to wait to get notified of a bad node.

Currently we are just duplicating the rule so it alerts earlier but looking to see if it can be modified directly using jsonnet config.

**Comment by brancz** [comment]
I think just lowering the default to 15m sounds fine :)

**Comment by mitchellmaler** [comment]
I just submitted PR #237

**Comment by paulfantom** [comment]
This can be closed as #237 is merged.

**Comment by mitchellmaler** [comment]
Closing since PR was merged.

**Comment by smarterclayton** [comment]
I think 15m is still too long for a few scenarios, such as network partition or node loss.  The node controller already is responsible for assessing a delay (which is also technically tunable and in the future should probably be node specific) - once that condition is met on the node object or on pods there should be a firing alert.  That is *not* the same as NotReady, but node.kubernetes.io/unreachable.

I'd suggest we add an alert that fires as soon as that taint is added - anyone who is experiencing continuous network disruption should already be tuning their grace period up so that it doesn't fire, or their workloads will get evicted.
