### ISSUE TITLE
Make range configurable in dashboard queries

### ISSUE THREAD

**Issue by serathius** [kubernetes-monitoring/kubernetes-mixin#36]
e. .g Dashboards like "K8s / Compute Resources / Cluster" uses query `sum(irate(container_cpu_usage_seconds_total[1m])) by (namespace)` 
That creates hidden dependency that scrape job can't run less frequent then sub 1m. 

I think range should be configurable

**Comment by tomwilkie** [comment]
> That creates hidden dependency that scrape job can't run less frequent then sub 1m.

Well technically, 30s - you need at least 2 data points for a rate to work reliably.  And realistically, your rate range should be 4x scrape, to deal with jitter etc - hence 1m, which is 4x 15s, the default scrape period.

> That creates hidden dependency that scrape job can't run less frequent then sub 1m.  I think range should be configurable

Sounds good to me!  Although I'd like to experiment using grafana's $__interval meta variable here, so that when you zoom out in Grafana, the rate duration also get larger: http://docs.grafana.org/reference/templating/#the-interval-variable

**Comment by ravishivt** [comment]
It would be nice to have it configurable but I'd recommend setting `2m` as the default for `rate` queries.  See https://github.com/kubernetes/ingress-nginx/pull/2884 for another project that made the same.

**Comment by omerlh** [comment]
Any update regarding this issue?

**Comment by omerlh** [comment]
Anyone facing a simpler issue, this is a quick jsonnet fix (that also add labels for grafana config map loader):
```jsonnet
{ 'grafana-dashboards-configmaps': 
       configMapList.new([
        configmap + configmap.mixin.metadata.withLabels({"grafana_dashboard": "1"}) 
        + configmap.withData({[item]: std.strReplace(configmap.data[item], '[1m]', '[2m]') for item in std.objectFields(configmap.data)})
        for configmap in kp.grafana.dashboardDefinitions.items
      ]) } + 
```

**Comment by metalmatze** [comment]
I don't think there are any plans to change it.

**Comment by brancz** [comment]
Why not use `_interval`? That should always pick a reasonable interval as it's based on screen real estate available.
