### ISSUE TITLE
kubernetes-apps alerts are mostly cause-based and probably shouldn't be critical

### ISSUE THREAD

**Issue by beorn7** [kubernetes-monitoring/kubernetes-mixin#395]
[A bunch of critical kubernetes-apps alerts](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/apps_alerts.libsonnet#L11-L148) are IMHO perfect examples for cause-based alerts, i.e. a single pod crashlooping may or may not be an immediate problem for the service. It's important to have those, but they should be warning-level, to be dealt with during work hours.

Obviously, the severity can be overridden, but that's true both ways. I suggest to have them as warnings, and whoever has a special case to make them critical can override the severity.

WDYT?

**Comment by brancz** [comment]
Agreed

**Comment by povilasv** [comment]
:+1:

**Comment by dudicoco** [comment]
@beorn7 @brancz @povilasv currently none of the kubernetes-apps alerts are critical, which I find very odd.

For example, I agree that a single pod in crashloop shouldn't be critical, however what if all of the pods in your deployment or 50% of them are crashlooping? There is no critical alert rule to indicate that downtime, of course you could say that the app should have additional monitoring in place but we can't make that assumption.

Another example is `KubeHpaMaxedOut` - if the HPA has reached max replicas the pods might start crashlooping due to OOM, and again we will have downtime and won't know about it.

**Comment by dudicoco** [comment]
@beorn7 @brancz @povilasv what's your take on this?

**Comment by dudicoco** [comment]
@beorn7 assuming that there is additional monitoring from the application, what would you consider a symptom based alert in the example of `KubeHpaMaxedOut`? 

I guess a symptom could be 5xx errors from the application, however, one could argue that if we were alerted when the hpa was maxed out action could taken to increase the max replicas before the application can't handle the load and starts returning 5xx errors.
