### ISSUE TITLE
Use job="apiserver" value in kubeApiserverSelector for cloud environment.

### ISSUE THREAD

**Issue by witold-gren** [kubernetes-monitoring/kubernetes-mixin#452]
Hi, I would like to ask about the naming of the apiserver metrics. (the exact: line https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/config.libsonnet#L27). All cloud providers use the name `apiserver` series to give access to apiserver metrics. Also I know that non cloud configuration (eg. kubeadm) use `kube-apiserver`. Is there a possibility to update this value to start using `apiserver`? It seems to me that most kubernets configuration exist in cloud environment. 

PS. Also I know, that we have configuration file to update this value. 😀

**Comment by metalmatze** [comment]
> Is there a possibility to update this value to start using apiserver?

Are you asking us if kubeadm can update their labels? The point of the configuration line you posted above is, so that you can easily go ahead and change the value from `apiserver` to `kube-apiserver`. :wink: 
So I agree, probably kubeadm should update to be a bit more consistent with others, but it really shouldn't be a problem to use it with this mixin.
