### ISSUE TITLE
Persistent Volume free space prediction should be configurable/more sophisticated

### ISSUE THREAD

**Issue by pkavajin** [kubernetes-monitoring/kubernetes-mixin#54]
In our case we have an indexing task which, when started, does a lot of initial writing.
But thats just initial stuff and I'm unsure whether linear prediction is the right thing to do in that case.
Not sure if we can go for a more sophisticated sampling, else I'd suggest to make the sampling time frame configurable.

@metalmatze any ideas on that one?

**Comment by metalmatze** [comment]
First of all, just to clarify, this issue is about the [KubePersistentVolumeFullInFourDays](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/storage_alerts.libsonnet#L24) alert.

@pkavajin, can you check wether changing the predict_linear duration or the amount is days is helping you?

@tomwilkie @brancz, WDYT should we make this configurable just like the certificate expiration durations?

**Comment by brancz** [comment]
> WDYT should we make this configurable just like the certificate expiration durations?

Generally sounds good to me, although even when configurable I think it's rather unlikely that there is going to be a one-size-fits all configuration for an entire cluster, but I guess the "highest" threshold as the common denominator is still better than none.
