### ISSUE TITLE
kubelet instances number inaccurate by using up metric

### ISSUE THREAD

**Issue by yeya24** [kubernetes-monitoring/kubernetes-mixin#658]
I am not sure if this is by design or not. The issue is that in the kubelet dashboard, https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/kubelet.libsonnet#L19 is used to count the number of `Running kubelets`.

However, I expect `Running kubelets` means the number of kubelet processes in the cluster, which equals to the number of nodes. But using `up{job="kubelet"}` is not equal to the number of nodes.  In [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/k8s-control-plane.libsonnet#L87), there are 3 endpoints to scrape for the `kubelet` serviceMonitor so the up count is actually 3x kubelet count.

**Comment by paulfantom** [comment]
This was fixed in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/601

**Comment by paulfantom** [comment]
We are no longer using `up` metric for finding number of running kubelets as seen in https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/kubelet.libsonnet?rgh-link-date=2021-08-10T18%3A59%3A15Z#L19. We are using `kubelet_node_name` since https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/601 was merged.

**Comment by yeya24** [comment]
thanks, looks like I need to bump the version.
