### ISSUE TITLE
KubePersistentVolumeFullInFourDays alert flaps for prometheus persistent volumes

### ISSUE THREAD

**Issue by point9repeating** [kubernetes-monitoring/kubernetes-mixin#98]
We are seeing this alert fire and resolve multiple times per day:
<img width="1622" alt="screen shot 2018-09-26 at 8 47 51 pm" src="https://user-images.githubusercontent.com/450588/46122435-7cbcbb00-c1cd-11e8-8140-5051801cbafd.png">

I believe this is partially because we're creating a bunch of short-running jobs/pods which creates a bunch of new series in prometheus, but I also think this alert might be a little too sensitive trying to predict 4 days growth off 1 hour (especially using a simple linear model).

If I set the prediction based on the last 24h, we wouldn't have any alerts:
<img width="1625" alt="screen shot 2018-09-26 at 8 46 12 pm" src="https://user-images.githubusercontent.com/450588/46122424-6b73ae80-c1cd-11e8-847e-761fe96e0370.png">

I'm not sure how the alert would behave in the first 24 hours with the above example.

**Comment by cbeneke** [comment]
Hi, this exact problem was fixed in https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/7fb348655dce603e415c12d090041b67438b1e7b. Please (update and) use the volumeFullPredictionSampleTime variable to fit your needs. The default switched from 1h to 6h in the same step (Which was sufficient for us to give more reasonable predictions).
